// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYL1k-5v-pPOCEWP98LxHvilB2hYVjgFc',
    appId: '1:407625670847:android:b9851dfe9537f7aafd660a',
    messagingSenderId: '407625670847',
    projectId: 'bookbridge-version1-desktop',
    storageBucket: 'bookbridge-version1-desktop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfDKhgeivY4s8hvmRW5Y0KI72T8zL11lw',
    appId: '1:407625670847:ios:6d5fe6cfc42c6ad5fd660a',
    messagingSenderId: '407625670847',
    projectId: 'bookbridge-version1-desktop',
    storageBucket: 'bookbridge-version1-desktop.firebasestorage.app',
    iosBundleId: 'com.example.bookbridgev1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHgv6Vudybn8OYFyAsf6csVkpq-sAQ7KI',
    appId: '1:407625670847:web:9aa794216ffa06bdfd660a',
    messagingSenderId: '407625670847',
    projectId: 'bookbridge-version1-desktop',
    authDomain: 'bookbridge-version1-desktop.firebaseapp.com',
    storageBucket: 'bookbridge-version1-desktop.firebasestorage.app',
    measurementId: 'G-NB4SS9624W',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfDKhgeivY4s8hvmRW5Y0KI72T8zL11lw',
    appId: '1:407625670847:ios:6d5fe6cfc42c6ad5fd660a',
    messagingSenderId: '407625670847',
    projectId: 'bookbridge-version1-desktop',
    storageBucket: 'bookbridge-version1-desktop.firebasestorage.app',
    iosBundleId: 'com.example.bookbridgev1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHgv6Vudybn8OYFyAsf6csVkpq-sAQ7KI',
    appId: '1:407625670847:web:d914701eb696e6d0fd660a',
    messagingSenderId: '407625670847',
    projectId: 'bookbridge-version1-desktop',
    authDomain: 'bookbridge-version1-desktop.firebaseapp.com',
    storageBucket: 'bookbridge-version1-desktop.firebasestorage.app',
    measurementId: 'G-LFM2J2GWZ3',
  );

}